// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3711.deepspace.subsystems;


import com.ctre.phoenix.motorcontrol.ControlMode;
import org.usfirst.frc3711.deepspace.TalonID;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Intake extends TalonSubsystem {
  private final Runnable talonTelemetry;


  public Intake() {
    super(Intake.class.getSimpleName(), TalonID.INTAKE.getId());
    talonTelemetry = TalonUtil.basicTelemetry(this);

  }


  @Override
  public void periodic() {
    super.periodic();
    talonTelemetry.run();

  }

  public boolean isRunning() {
    return talon.getOutputCurrent() != 0;
  }

  public void run(boolean forward) {
    double out = forward ? 1.0 : -1.0;
    talon.set(ControlMode.PercentOutput, out);
  }

  public void inhale() {
    talon.set(ControlMode.PercentOutput, 1.0);
  }

  public void exhale() {
    talon.set(ControlMode.PercentOutput, -1.0);
  }

  public void stop() {
    talon.neutralOutput();
  }

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

  // Put methods for controlling this subsystem
  // here. Call these from Commands.

}

