// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3711.FRC2019.subsystems;


import org.usfirst.frc3711.FRC2019.TalonID;
import org.usfirst.frc3711.FRC2019.talon.TalonLiveWindowSupport;
import org.usfirst.frc3711.FRC2019.talon.TalonTelemetry;

import edu.wpi.first.wpilibj.Sendable;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
import edu.wpi.first.wpilibj.shuffleboard.ShuffleboardTab;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Arm extends TalonSubsystem {
public ShuffleboardTab tab;

    public Arm() {
      super(Arm.class.getSimpleName(), TalonID.ARM.getId());
      tab = Shuffleboard.getTab(Arm.class.getSimpleName());
        Sendable s = new TalonTelemetry.MotorIOSendable(talon);
        addChild("motor io", s);
        Sendable s2 = new TalonTelemetry.SensorCollectionSendable(talon.getSensorCollection());
        addChild("sensor collection",s2);
      tab.add(s);
      tab.add(s2);

        addChild("ArmPID", new TalonLiveWindowSupport(talon));

    }

    @Override // Put code here to be run every loop
    public void initDefaultCommand() {

    }

    @Override
    void configureTalon() {
        super.configureTalon();
        talon.setInverted(true);

      
    }

    @Override
    public void periodic() {
        super.periodic();
            SmartDashboard.putNumber("Arm position", talon.getSensorCollection().getQuadraturePosition());
            SmartDashboard.putNumber("Arm position2", talon.getSelectedSensorPosition());
    }

}

