package org.usfirst.frc3711.FRC2019.subsystems;

import com.ctre.phoenix.motorcontrol.Faults;
import com.ctre.phoenix.motorcontrol.InvertType;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.shuffleboard.BuiltInLayouts;
import org.usfirst.frc3711.FRC2019.TalonID;
import org.usfirst.frc3711.FRC2019.commands.DrivewithJoystick;

import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
import edu.wpi.first.wpilibj.shuffleboard.ShuffleboardTab;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

public class Chassis extends Subsystem {


    private WPI_TalonSRX leftFront;
    private WPI_TalonSRX leftRear;

    private WPI_TalonSRX rightFront;
    private WPI_TalonSRX rightRear;

    private DifferentialDrive drive;
    public ShuffleboardTab tab;
    //private NetworkTableEntry leftOutput, leftRearOutput, rightOutput,rightRearOutput;




    public Chassis() {
        leftFront = new WPI_TalonSRX(TalonID.LEFT_FRONT.getId());
        addChild("left front",leftFront);

        leftRear = new WPI_TalonSRX(TalonID.LEFT_REAR.getId());

        
        rightFront = new WPI_TalonSRX(TalonID.RIGHT_FRONT.getId());
        addChild("right front",rightFront);

        rightRear = new WPI_TalonSRX(TalonID.RIGHT_REAR.getId());
        

        
        
        drive = new DifferentialDrive(leftFront, rightFront);
        addChild("Drive",drive);

        drive.setSafetyEnabled(false);
        leftFront.setSafetyEnabled(false);
        leftRear.setSafetyEnabled(false);
        rightFront.setSafetyEnabled(false);
        rightRear.setSafetyEnabled(false);

        drive.setExpiration(0.1);
        drive.setMaxOutput(1.0);

        drive.setRightSideInverted(false);

        configureTalons();

        tab = Shuffleboard.getTab(Chassis.class.getSimpleName());

        tab.getLayout("left", BuiltInLayouts.kList)
                .add(leftFront).getParent()
                .add(leftRear).getParent()
           .getLayout("right",BuiltInLayouts.kList)
                .add(rightFront).getParent()
                .add(rightRear);


        tab.add(drive);
      //  tab.add(new DrivewithJoystick());

    }
    private void configureTalons(){
        rightFront.configFactoryDefault();
        rightRear.configFactoryDefault();
        leftFront.configFactoryDefault();
        leftRear.configFactoryDefault();

        rightRear.follow(rightFront);
        leftRear.follow(leftFront);

        rightFront.setInverted(true);
        leftFront.setInverted(false);

        rightRear.setInverted(InvertType.FollowMaster);
        leftRear.setInverted(InvertType.FollowMaster);

        rightFront.setSensorPhase(true);
        leftFront.setSensorPhase(true);

        
    }

    private void telemetry(){

        Faults leftFaults = new Faults();
        Faults rightFaults = new Faults();
        leftFront.getFaults(leftFaults);
        rightFront.getFaults(rightFaults);
        if(leftFaults.hasAnyFault()){
            DriverStation.reportWarning(leftFaults.toString(), false);
        }
        if(rightFaults.hasAnyFault()){
            DriverStation.reportWarning(rightFaults.toString(), false);
        }
    }

    public void drive(double forward, double turn){
        drive.arcadeDrive(forward, turn);
    }

    @Override
    public void initDefaultCommand() {
        setDefaultCommand(new DrivewithJoystick());
    }

    @Override
    public void periodic() {
        telemetry();
    }

}

